### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.cucumber.ScenarioReporter

### ISSUE THREAD

**Issue by vrajasg** [reportportal/agent-java-cucumber5#10]
Unable to integrate _**agent-java-cucumber5**_ with **_cucumber-java 5.6.x_** 
Am using valid compatible cucumber agents as provided [here](https://github.com/reportportal/agent-java-cucumber#scenario-reporter) but still seeing the plugin error.

Unfortunately didn't found example for cucumber-agents 5.x (or higher), refer [examples-java](https://github.com/reportportal/examples-java) 

> Here is the branch am currently working, please feel to refer to it.
> https://github.com/vrajasg/cucumber/tree/reportportal-cucumberJvm-integration
> 
> Run below command to see the error
> mvn -U clean test -Dcucumber.filter.tags="@smoke" -Durl=https://google.co.uk

![Screenshot 2020-12-27 at 22 28 44](https://user-images.githubusercontent.com/10340041/103180968-5cd83e00-4893-11eb-84bd-222277ca2fc2.png)

**Comment by vrajasg** [comment]
Issue resolved after updating Cucumber-java and agent-java-cucumber. Integration works fine now.

Updated to:
- cucumber-java to 6.x 
- RP agent to cucumber6

**Comment by akadnikov** [comment]
I am facing with same trouble. Are there any fixes for cucumber 5?
