### ISSUE TITLE
How to create a single launch in parallel execution using cucumber

### ISSUE THREAD

**Issue by cvarshn-cloud** [reportportal/agent-java-cucumber5#12]
@lexecon @abotalov @avarabyeu @HardNorth @pbortnik 
I am using cucumber JVM parallel plugin to run test cases parallelly but I am getting multiple launches when I run my test suite. How to get only single launch for parallel execution.

**Comment by HardNorth** [comment]
@cvarshn-cloud Could you please provide example project?
And please, do not highlight everyone. People here work on different areas.

**Comment by HardNorth** [comment]
Abandoned
