### ISSUE TITLE
Support for Cucumber-Java 5+

### ISSUE THREAD

**Issue by dipanjan-it** [reportportal/agent-java-cucumber5#4]
Hello,

Could you please let us know when can we expect an updated version of agent to support Cucumber-Java 5 version? We have upgraded our framework to use 5.6.0 version of Cucumber-Java and seems like the agent is not compatible with it.

Thanks!

**Comment by HardNorth** [comment]
It's still in the process of the implementation but there is an alpha version.

**Comment by HardNorth** [comment]
https://github.com/reportportal/agent-java-cucumber5/releases/tag/5.0.0-RC-1
